name: Publish
on:
  push:
    branches:
      - main
    paths:
      - 'packages/react-scripts/**'
      - '.github/workflows/publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PACKAGE_TOKEN }}" > ~/.npmrc

      - name: Cache node modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: packages/react-scripts/node_modules
          key: spce-react-scripts-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          cd packages/react-scripts
          npm install

      - name: Publish to NPM Package Registry
        run: |
          cd packages/react-scripts
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGE_TOKEN }}
